
project_id = "bmopbbkfxkgzlbmhhgox"

[global.env_variables]

[[analyzers]]
name = "openai"
config = { api_key = "env:OPENAI_API_KEY" }

[[analyzers]]
name = "anthropic"
config = { api_key = "env:ANTHROPIC_API_KEY" }

[[functions]]
name = "generate-section-content"
verify_jwt = false
import_map = "import_map.json"

[[functions]]
name = "analyze-rfp"
verify_jwt = true
import_map = "import_map.json"

[[functions]]
name = "check-subscription"
verify_jwt = true

[[functions]]
name = "cancel-subscription"
verify_jwt = true

[[functions]]
name = "create-checkout-session"
verify_jwt = true

[[functions]]
name = "stripe-webhook"
verify_jwt = false
import_map = "import_map.json"

[[functions]]
name = "generate-proposal-outline"
verify_jwt = true
import_map = "import_map.json"

[[functions]]
name = "evaluate-proposal"
verify_jwt = true
import_map = "import_map.json"

[[functions]]
name = "parse-knowledge-file"
verify_jwt = true

[[functions]]
name = "parse-existing-knowledge-files"
verify_jwt = true

[[functions]]
name = "renew-subscription"
verify_jwt = true

[[functions]]
name = "get-user-roles"
verify_jwt = true

[[functions]]
name = "get-pending-invitation"
verify_jwt = true

[[functions]]
name = "get-beta-invitations"
verify_jwt = true

[[functions]]
name = "send-email"
verify_jwt = true
import_map = "import_map.json"

[[functions]]
name = "email-webhooks"
verify_jwt = false
import_map = "import_map.json"
