import { Button } from '@/components/ui/button';
import { Download, Save, Loader2, Lock } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { useState } from 'react';
import { useSubscriptionFeatures } from '@/hooks/use-subscription-features';
import { GatedFeatureModal } from '@/components/subscription/GatedFeatureModal';

interface ExportPanelProps {
  designId: string;
  isSaving: boolean;
  onSave: () => Promise<void>;
}

const TIER_ORDER: Record<string, number> = {
  starter: 0, growth: 1, business: 2, enterprise: 3,
};

export function ExportPanel({ designId, isSaving, onSave }: ExportPanelProps) {
  const [exporting, setExporting] = useState(false);
  const [showGateModal, setShowGateModal] = useState(false);
  const { plan } = useSubscriptionFeatures();

  const isExportLocked = (TIER_ORDER[plan] ?? 0) < TIER_ORDER.growth;

  const handleExportPdf = async () => {
    if (isExportLocked) {
      setShowGateModal(true);
      return;
    }

    setExporting(true);
    try {
      await onSave();

      const { data, error } = await supabase.functions.invoke('export-proposal-pdf', {
        body: { designId, plan },
      });

      if (error) throw error;

      if (data?.url) {
        window.open(data.url, '_blank');
        toast.success('PDF generated successfully');
      } else if (data?.html) {
        let html = data.html;
        if (plan === 'starter') {
          const watermark = `<div style="position:fixed;bottom:0;left:0;right:0;text-align:center;padding:10px;background:rgba(248,248,248,0.95);border-top:1px solid #e0e0e0;font-size:10pt;font-style:italic;color:rgba(0,0,0,0.3);font-family:sans-serif;">Generated by OptiRFP Free — <a href="${window.location.origin}/subscription" style="color:rgba(59,130,246,0.5);text-decoration:underline;font-style:italic;">Upgrade to remove watermark</a></div>`;
          html = html.replace('</body>', `${watermark}</body>`);
        }
        const w = window.open('', '_blank');
        if (w) {
          w.document.write(html);
          w.document.close();
          setTimeout(() => w.print(), 500);
        }
        toast.success('Print dialog opened — save as PDF');
      }
    } catch (err: any) {
      console.error('Export failed:', err);
      toast.error('Export failed. Please try again.');
    } finally {
      setExporting(false);
    }
  };

  return (
    <>
      <div className="flex gap-2">
        <Button variant="outline" size="sm" onClick={onSave} disabled={isSaving}>
          {isSaving ? <Loader2 className="h-4 w-4 animate-spin mr-1" /> : <Save className="h-4 w-4 mr-1" />}
          Save
        </Button>
        <Button size="sm" onClick={handleExportPdf} disabled={exporting} className="relative">
          {exporting ? (
            <Loader2 className="h-4 w-4 animate-spin mr-1" />
          ) : isExportLocked ? (
            <Lock className="h-4 w-4 mr-1" />
          ) : (
            <Download className="h-4 w-4 mr-1" />
          )}
          Export PDF
        </Button>
      </div>

      <GatedFeatureModal
        open={showGateModal}
        onOpenChange={setShowGateModal}
        featureName="Document Export"
        requiredTier="growth"
        description="Export your proposals as professional PDF and Word documents, ready for submission."
        benefits={[
          "Export proposals as professional Word (.docx) documents",
          "Export as PDF for easy sharing and printing",
          "3 built-in templates (Professional, Modern, Minimal)",
          "Apply your brand guidelines (logo, colors, fonts)",
        ]}
      />
    </>
  );
}
