import { Button } from '@/components/ui/button';
import { Download, Save, Loader2 } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { useState } from 'react';
import { useSubscriptionFeatures } from '@/hooks/use-subscription-features';

interface ExportPanelProps {
  designId: string;
  isSaving: boolean;
  onSave: () => Promise<void>;
}

export function ExportPanel({ designId, isSaving, onSave }: ExportPanelProps) {
  const [exporting, setExporting] = useState(false);
  const { plan } = useSubscriptionFeatures();

  const handleExportPdf = async () => {
    setExporting(true);
    try {
      // Save first
      await onSave();

      const { data, error } = await supabase.functions.invoke('export-proposal-pdf', {
        body: { designId, plan },
      });

      if (error) throw error;

      if (data?.url) {
        window.open(data.url, '_blank');
        toast.success('PDF generated successfully');
      } else if (data?.html) {
        // For starter plan, inject watermark into fallback HTML
        let html = data.html;
        if (plan === 'starter') {
          const watermark = `<div style="position:fixed;bottom:0;left:0;right:0;text-align:center;padding:8px;background:#f8f8f8;border-top:1px solid #e0e0e0;font-size:11px;color:#888;font-family:sans-serif;">Generated by OptiRFP Free — <a href="${window.location.origin}/subscription" style="color:#3b82f6;text-decoration:underline;">Upgrade to remove</a></div>`;
          html = html.replace('</body>', `${watermark}</body>`);
        }
        const w = window.open('', '_blank');
        if (w) {
          w.document.write(html);
          w.document.close();
          setTimeout(() => w.print(), 500);
        }
        toast.success('Print dialog opened — save as PDF');
      }
    } catch (err: any) {
      console.error('Export failed:', err);
      toast.error('Export failed. Please try again.');
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="flex gap-2">
      <Button variant="outline" size="sm" onClick={onSave} disabled={isSaving}>
        {isSaving ? <Loader2 className="h-4 w-4 animate-spin mr-1" /> : <Save className="h-4 w-4 mr-1" />}
        Save
      </Button>
      <Button size="sm" onClick={handleExportPdf} disabled={exporting}>
        {exporting ? <Loader2 className="h-4 w-4 animate-spin mr-1" /> : <Download className="h-4 w-4 mr-1" />}
        Export PDF
      </Button>
    </div>
  );
}
