
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Copy } from "lucide-react";
import { toast } from "sonner";
import { ProposalSection } from "../useProposalSections";
import ReactMarkdown from "react-markdown";
import { SubmitToKnowledgeBaseButton } from "./SubmitToKnowledgeBaseButton";
import { useSubscriptionFeatures } from "@/hooks/use-subscription-features";
import { useSubscription } from "@/hooks/use-subscription";
import { useNavigate } from "react-router-dom";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

interface CompiledViewProps {
  sections: ProposalSection[];
  projectId: string;
  projectTitle?: string;
}

export function CompiledView({ sections, projectId, projectTitle }: CompiledViewProps) {
  const [isExpanded, setIsExpanded] = useState(false);
  const [showMarkdown, setShowMarkdown] = useState(true);
  const { plan } = useSubscriptionFeatures();
  const { data: subscription } = useSubscription();
  const navigate = useNavigate();

  const showWatermark = plan === 'starter' && subscription?.status !== 'trialing';
  const watermarkText = "\n\n---\n_Generated by OptiRFP Free — Upgrade to remove watermark_";

  const compiledContent = sections
    .map((section) => {
      const title = section.section_title;
      const content = section.content || "";
      return content ? `# ${title}\n\n${content}` : `# ${title}\n\n*[Content not generated yet]*`;
    })
    .join("\n\n---\n\n");

  const handleCopy = async () => {
    try {
      const content = showWatermark ? compiledContent + watermarkText : compiledContent;
      await navigator.clipboard.writeText(content);
      toast.success("Copied to clipboard!");
      if (showWatermark) {
        toast.info("This export includes a watermark. Upgrade to remove it.", {
          action: { label: "Upgrade Now", onClick: () => navigate("/subscription") },
        });
      }
    } catch (error) {
      toast.error("Failed to copy to clipboard");
    }
  };

  return (
    <div className="p-2 sm:p-6">
      <Card>
        <CardHeader className="p-3 sm:p-6">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
            <div>
              <CardTitle className="text-xl sm:text-2xl font-semibold leading-none tracking-tight">
                Compiled Proposal
              </CardTitle>
              <CardDescription>
                View and copy your complete proposal
              </CardDescription>
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => setShowMarkdown(!showMarkdown)}
                className="bg-brand-green hover:bg-brand-green-dark text-white border-brand-green hover:border-brand-green-dark text-xs sm:text-sm"
              >
                {showMarkdown ? "Show Raw" : "Show Formatted"}
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={handleCopy}
                className="bg-brand-green hover:bg-brand-green-dark text-white border-brand-green hover:border-brand-green-dark flex items-center gap-2 text-xs sm:text-sm"
              >
                <Copy className="h-4 w-4" />
                Copy
              </Button>
              <SubmitToKnowledgeBaseButton
                proposalContent={compiledContent}
                projectId={projectId}
                projectTitle={projectTitle}
              />
            </div>
          </div>
        </CardHeader>
        <CardContent className="p-3 sm:p-6 pt-0">
          {showMarkdown ? (
            <div 
              className={`relative prose dark:prose-invert max-w-none border rounded-md p-3 sm:p-4 bg-background overflow-y-auto ${
                isExpanded ? "min-h-[500px]" : "min-h-[200px]"
              }`}
              onClick={() => setIsExpanded(!isExpanded)}
            >
              <ReactMarkdown>{compiledContent}</ReactMarkdown>
              {showWatermark && (
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <div className="sticky bottom-0 left-0 right-0 text-center py-2 bg-muted/80 backdrop-blur-sm border-t text-[10pt] italic text-foreground/30">
                        Generated by OptiRFP Free — Upgrade to remove watermark
                      </div>
                    </TooltipTrigger>
                    <TooltipContent>
                      <p>Upgrade to remove watermark</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              )}
            </div>
          ) : (
            <div className="relative">
              <Textarea
                value={compiledContent}
                readOnly
                className={`resize-none ${isExpanded ? "min-h-[500px]" : "min-h-[200px]"}`}
                onClick={() => setIsExpanded(!isExpanded)}
              />
              {showWatermark && (
                <div className="text-center py-2 bg-muted/80 border-t text-[10pt] italic text-foreground/30">
                  Generated by OptiRFP Free — Upgrade to remove watermark
                </div>
              )}
            </div>
          )}
          {/* Document Stats */}
          {(() => {
            const words = compiledContent.trim().split(/\s+/).filter(Boolean).length;
            const chars = compiledContent.length;
            const pages = Math.ceil(words / 250);
            return (
              <div className="flex items-center gap-4 mt-2 text-xs text-muted-foreground">
                <span>{words.toLocaleString()} words</span>
                <span>{chars.toLocaleString()} characters</span>
                <span>~{pages} {pages === 1 ? 'page' : 'pages'}</span>
              </div>
            );
          })()}
        </CardContent>
      </Card>
    </div>
  );
}
