
import { useState, useRef, useEffect, useMemo } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Copy, Printer, List, Download, FileText, FileType, Loader2 } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { toast } from "sonner";
import { ProposalSection } from "../useProposalSections";
import { SubmitToKnowledgeBaseButton } from "./SubmitToKnowledgeBaseButton";
import { useSubscriptionFeatures } from "@/hooks/use-subscription-features";
import { useSubscription } from "@/hooks/use-subscription";
import { useNavigate } from "react-router-dom";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { countWords } from "@/utils/wordCount";
import { cn } from "@/lib/utils";
import DOMPurify from "dompurify";
import { supabase } from "@/integrations/supabase/client";

const OPTIRFP_LOGO_PATH = "/lovable-uploads/e3257c71-ec26-4f77-b50f-f3115dd1a320.png";
const WATERMARK_PHRASE = "Generated with OptiRFP Free — Upgrade to remove watermark";

interface CompiledViewProps {
  sections: ProposalSection[];
  projectId: string;
  projectTitle?: string;
}

export function CompiledView({ sections, projectId, projectTitle }: CompiledViewProps) {
  const [showRaw, setShowRaw] = useState(false);
  const [activeId, setActiveId] = useState<string | null>(null);
  const [showToc, setShowToc] = useState(true);
  const { plan } = useSubscriptionFeatures();
  const { data: subscription } = useSubscription();
  const navigate = useNavigate();
  const contentRef = useRef<HTMLDivElement>(null);

  const showWatermark = plan === 'starter' && subscription?.status !== 'trialing';

  // Build plain-text version for raw view and copy
  const rawContent = useMemo(() =>
    sections.map((s) => {
      const text = s.content
        ? s.content.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim()
        : "[Content not generated yet]";
      return `# ${s.section_title}\n\n${text}`;
    }).join("\n\n---\n\n"),
    [sections]
  );

  // Stats from actual content (strip HTML)
  const stats = useMemo(() => {
    const totalWords = sections.reduce((sum, s) => sum + countWords(s.content || ""), 0);
    const chars = sections.reduce((sum, s) => sum + (s.content || "").replace(/<[^>]*>/g, "").length, 0);
    const pages = Math.ceil(totalWords / 250);
    const readMin = Math.ceil(totalWords / 200);
    return { totalWords, chars, pages, readMin };
  }, [sections]);

  // Scroll spy
  useEffect(() => {
    if (!contentRef.current) return;
    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            setActiveId(entry.target.id);
          }
        }
      },
      { root: contentRef.current, rootMargin: "-20% 0px -70% 0px", threshold: 0 }
    );
    const headings = contentRef.current.querySelectorAll("[data-section-id]");
    headings.forEach((h) => observer.observe(h));
    return () => observer.disconnect();
  }, [sections]);

  const scrollToSection = (sectionId: string) => {
    const el = contentRef.current?.querySelector(`[data-section-id="${sectionId}"]`);
    el?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  const handleCopy = async () => {
    try {
      const content = showWatermark ? rawContent + "\n\n---\nGenerated by OptiRFP Free — Upgrade to remove watermark" : rawContent;
      await navigator.clipboard.writeText(content);
      toast.success("Copied to clipboard!");
      if (showWatermark) {
        toast.info("This export includes a watermark. Upgrade to remove it.", {
          action: { label: "Upgrade Now", onClick: () => navigate("/subscription") },
        });
      }
    } catch {
      toast.error("Failed to copy to clipboard");
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const [exporting, setExporting] = useState<null | "pdf" | "doc" | "docx">(null);

  const runExport = async (format: "pdf" | "doc" | "docx") => {
    setExporting(format);
    try {
      const logoUrl = `${window.location.origin}${OPTIRFP_LOGO_PATH}`;
      const { data, error } = await supabase.functions.invoke("export-proposal-pdf", {
        body: { projectId, plan, format, logoUrl },
      });
      if (error) throw error;

      if (format === "pdf") {
        const html = (data as { html?: string })?.html;
        if (!html) throw new Error("No HTML returned");
        const w = window.open("", "_blank");
        if (w) {
          w.document.write(html);
          w.document.close();
          setTimeout(() => w.print(), 500);
          toast.success("Print dialog opened — save as PDF");
        }
      } else {
        const { filename, mimeType, base64 } = data as { filename: string; mimeType: string; base64: string };
        if (!base64) throw new Error("No file returned");
        const bin = atob(base64);
        const bytes = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
        const blob = new Blob([bytes], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        a.remove();
        URL.revokeObjectURL(url);
        toast.success(`Exported ${filename}`);
      }

      if (showWatermark) {
        toast.info("This export includes a watermark. Upgrade to remove it.", {
          action: { label: "Upgrade", onClick: () => navigate("/subscription") },
        });
      }
    } catch (err) {
      console.error("Export failed:", err);
      toast.error("Export failed. Please try again.");
    } finally {
      setExporting(null);
    }
  };

  return (
    <div className="p-2 sm:p-6">
      <Card>
        <CardHeader className="p-3 sm:p-6">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
            <div>
              <CardTitle className="text-xl sm:text-2xl font-semibold leading-none tracking-tight">
                Compiled Proposal
              </CardTitle>
              <CardDescription>
                View, copy, or print your complete proposal
              </CardDescription>
            </div>
            <div className="flex gap-2 flex-wrap">
              <Button
                variant="outline"
                size="sm"
                onClick={() => setShowToc(!showToc)}
                className="gap-1.5 text-xs sm:text-sm"
              >
                <List className="h-4 w-4" />
                {showToc ? "Hide" : "Show"} ToC
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() => setShowRaw(!showRaw)}
                className="text-xs sm:text-sm"
              >
                {showRaw ? "Show Formatted" : "Show Raw"}
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={handlePrint}
                className="gap-1.5 text-xs sm:text-sm"
              >
                <Printer className="h-4 w-4" />
                Print
              </Button>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button
                    variant="outline"
                    size="sm"
                    disabled={exporting !== null}
                    className="gap-1.5 text-xs sm:text-sm"
                  >
                    {exporting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
                    Export
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="w-48">
                  <DropdownMenuItem onClick={() => runExport("pdf")} className="gap-2">
                    <FileText className="h-4 w-4" /> Export as PDF
                  </DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem onClick={() => runExport("docx")} className="gap-2">
                    <FileType className="h-4 w-4" /> Export as Word (.docx)
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => runExport("doc")} className="gap-2">
                    <FileType className="h-4 w-4" /> Export as Word (.doc)
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
              <Button
                variant="outline"
                size="sm"
                onClick={handleCopy}
                className="bg-brand-green hover:bg-brand-green-dark text-white border-brand-green hover:border-brand-green-dark flex items-center gap-2 text-xs sm:text-sm"
              >
                <Copy className="h-4 w-4" />
                Copy All
              </Button>
              <SubmitToKnowledgeBaseButton
                proposalContent={rawContent}
                projectId={projectId}
                projectTitle={projectTitle}
              />
            </div>
          </div>
        </CardHeader>
        <CardContent className="p-3 sm:p-6 pt-0">
          <div className="flex gap-4">
            {/* Scroll-spy Table of Contents sidebar */}
            {showToc && sections.length > 0 && (
              <nav className="hidden md:block w-48 flex-shrink-0 sticky top-4 self-start max-h-[70vh] overflow-y-auto print:hidden">
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Contents</p>
                <ul className="space-y-1 border-l border-border pl-3">
                  {sections.map((s, i) => (
                    <li key={s.section_id}>
                      <button
                        onClick={() => scrollToSection(s.section_id)}
                        className={cn(
                          "text-left text-xs py-1 w-full truncate transition-colors hover:text-foreground",
                          activeId === `section-${s.section_id}`
                            ? "text-foreground font-medium border-l-2 border-primary -ml-[13px] pl-[11px]"
                            : "text-muted-foreground"
                        )}
                      >
                        {i + 1}. {s.section_title}
                      </button>
                    </li>
                  ))}
                </ul>
              </nav>
            )}

            {/* Main content */}
            <div className="flex-1 min-w-0">
              {showRaw ? (
                <Textarea
                  value={rawContent}
                  readOnly
                  className="resize-none min-h-[500px] font-mono text-xs"
                />
              ) : (
                <div
                  ref={contentRef}
                  className="compiled-proposal-content border rounded-md p-4 sm:p-6 bg-background overflow-y-auto max-h-[70vh] print:max-h-none print:overflow-visible"
                >
                  {sections.map((section, idx) => (
                    <div
                      key={section.section_id}
                      id={`section-${section.section_id}`}
                      data-section-id={`section-${section.section_id}`}
                      className={cn(idx > 0 && "mt-8 pt-8 border-t border-border")}
                    >
                      <h2 className="text-xl font-bold mb-4 text-foreground">{section.section_title}</h2>
                      {section.content ? (
                        <div
                          className="prose prose-sm dark:prose-invert max-w-none"
                          dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(section.content, { USE_PROFILES: { html: true } }) }}
                        />
                      ) : (
                        <p className="text-muted-foreground italic">Content not generated yet</p>
                      )}
                    </div>
                  ))}
                  {showWatermark && (
                    <TooltipProvider>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <div className="mt-8 pt-4 text-center border-t text-[10pt] italic text-foreground/30">
                            Generated by OptiRFP Free — Upgrade to remove watermark
                          </div>
                        </TooltipTrigger>
                        <TooltipContent>
                          <p>Upgrade to remove watermark</p>
                        </TooltipContent>
                      </Tooltip>
                    </TooltipProvider>
                  )}
                </div>
              )}

              {/* Document Stats */}
              <div className="flex items-center gap-4 mt-2 text-xs text-muted-foreground">
                <span>{stats.totalWords.toLocaleString()} words</span>
                <span>{stats.chars.toLocaleString()} characters</span>
                <span>~{stats.pages} {stats.pages === 1 ? "page" : "pages"}</span>
                <span>~{stats.readMin} min read</span>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
