import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Loader2, Wand, Download, RefreshCw, FileText, Copy, CheckCircle, ChevronDown } from "lucide-react";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { SubmitToKnowledgeBaseButton } from "@/components/project/proposal-draft/components/SubmitToKnowledgeBaseButton";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/components/AuthProvider";
import { AIProgress } from "@/components/shared/AIProgress";
import { useSubscriptionFeatures } from "@/hooks/use-subscription-features";
import { useSubscription } from "@/hooks/use-subscription";
import { useNavigate } from "react-router-dom";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

interface AutoGeneratedProposalProps {
  projectId: string;
  analysis: string | null;
  proposalOutline: string | null;
}

interface GenerationStatus {
  status: 'not_started' | 'in_progress' | 'completed' | 'failed';
  progress: number;
  currentSection?: string;
  error?: string;
}

interface ProposalMetadata {
  generatedAt: string;
  totalProcessingTime: number;
  sectionsGenerated: number;
  sectionsSuccessful?: number;
  sectionsFailed?: number;
  averageQuality: number;
  averageConfidence: number;
  sectionMetrics: Array<{
    section: string;
    quality: number;
    confidence: number;
    processingTime: number;
    modelUsed?: string;
    costTier?: string;
  }>;
  failedSections?: Array<{
    title: string;
    error: string;
  }>;
  costOptimization?: {
    enabled: boolean;
    avgCostReduction: number;
    modelsUsed: { [key: string]: number };
    tierDistribution: { low: number; medium: number; high: number };
    originalKnowledgeLength: number;
    optimizedContextUsed: boolean;
  };
}

export function AutoGeneratedProposal({ 
  projectId, 
  analysis, 
  proposalOutline 
}: AutoGeneratedProposalProps) {
  const { session } = useAuth();
  const user = session?.user;
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationStatus, setGenerationStatus] = useState<GenerationStatus>({
    status: 'not_started',
    progress: 0
  });
  const [generatedProposal, setGeneratedProposal] = useState<string | null>(null);
  const [proposalMetadata, setProposalMetadata] = useState<ProposalMetadata | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleGenerateProposal = async () => {
    if (!user?.id || !analysis || !proposalOutline) {
      toast.error("Missing required data", {
        description: "Please ensure you have completed the RFP analysis and proposal outline first."
      });
      return;
    }

    setIsGenerating(true);
    setError(null);
    setGenerationStatus({ status: 'in_progress', progress: 0 });

    try {
      console.log('Starting chunked proposal generation...');
      
      // First, extract all sections from the outline
      const allSections = extractSectionsFromOutline(proposalOutline);
      const CHUNK_SIZE = 6; // Process 6 sections per chunk to stay under timeout limits
      const chunks = [];
      
      // Split sections into chunks
      for (let i = 0; i < allSections.length; i += CHUNK_SIZE) {
        chunks.push(allSections.slice(i, i + CHUNK_SIZE));
      }
      
      console.log(`Generated ${chunks.length} chunks with ${allSections.length} total sections`);
      
      // Process chunks sequentially
      const allSectionResults: any[] = [];
      let combinedProposal = '';
      let combinedMetadata = null;
      
      for (let chunkIndex = 0; chunkIndex < chunks.length; chunkIndex++) {
        const currentChunk = chunks[chunkIndex];
        const chunkProgress = (chunkIndex / chunks.length) * 100;
        
        setGenerationStatus({ 
          status: 'in_progress', 
          progress: chunkProgress,
          currentSection: `Processing chunk ${chunkIndex + 1}/${chunks.length} (${currentChunk[0]}...)`
        });
        
        console.log(`Processing chunk ${chunkIndex + 1}/${chunks.length}:`, currentChunk);
        
        const { data, error: functionError } = await supabase.functions.invoke(
          'generate-full-proposal',
          {
            body: {
              projectId,
              userId: user.id,
              strictMode: false,
              sections: currentChunk,
              chunkIndex,
              totalChunks: chunks.length
            }
          }
        );

        if (functionError) throw functionError;

        if (data.success) {
          // Collect section results
          if (data.sectionsData) {
            allSectionResults.push(...data.sectionsData);
          }
          
          // Update progress
          const newProgress = ((chunkIndex + 1) / chunks.length) * 100;
          setGenerationStatus({ 
            status: 'in_progress', 
            progress: newProgress,
            currentSection: chunkIndex + 1 === chunks.length ? 'Finalizing proposal...' : `Completed chunk ${chunkIndex + 1}/${chunks.length}`
          });
          
          // Store metadata from the last chunk
          if (chunkIndex === chunks.length - 1) {
            combinedMetadata = data.metadata;
          }
        } else {
          throw new Error(data.error || `Failed to generate chunk ${chunkIndex + 1}`);
        }
      }
      
      // Combine all sections into final proposal
      combinedProposal = allSectionResults
        .map(result => `# ${result.sectionTitle}\n\n${result.content}`)
        .join('\n\n---\n\n');
      
      // Create combined metadata
      const totalProcessingTime = combinedMetadata?.totalProcessingTime || 0;
      const finalMetadata = {
        ...combinedMetadata,
        sectionsGenerated: allSectionResults.length,
        sectionsSuccessful: allSectionResults.filter(r => r.quality.overallScore > 0).length,
        sectionsFailed: allSectionResults.filter(r => r.quality.overallScore === 0).length,
        averageQuality: allSectionResults.reduce((sum, r) => sum + r.quality.overallScore, 0) / allSectionResults.length,
        averageConfidence: allSectionResults.reduce((sum, r) => sum + r.quality.modelConfidence, 0) / allSectionResults.length,
        sectionMetrics: allSectionResults.map(result => ({
          section: result.sectionTitle,
          quality: result.quality.overallScore,
          confidence: result.quality.modelConfidence,
          processingTime: result.processingTime
        }))
      };

      setGeneratedProposal(combinedProposal);
      setProposalMetadata(finalMetadata);
      setGenerationStatus({ status: 'completed', progress: 100 });
      
      toast.success("Full proposal generated successfully!", {
        description: `Generated ${allSectionResults.length} sections in ${Math.round(totalProcessingTime / 1000)}s using chunked processing`
      });

    } catch (err) {
      console.error('Error generating full proposal:', err);
      const errorMessage = err instanceof Error ? err.message : 'Failed to generate proposal';
      setError(errorMessage);
      setGenerationStatus({ status: 'failed', progress: 0, error: errorMessage });
      
      toast.error("Failed to generate proposal", {
        description: errorMessage
      });
    } finally {
      setIsGenerating(false);
    }
  };

  // Helper function to extract sections from outline
  const extractSectionsFromOutline = (outline: string): string[] => {
    const sections = [];
    const lines = outline.split('\n');
    
    for (const line of lines) {
      const trimmed = line.trim();
      // Look for section headers (lines that start with numbers, bullets, or are in title case)
      if (trimmed && (
        /^\d+\./.test(trimmed) || 
        /^[-*•]/.test(trimmed) ||
        /^[A-Z][a-z]/.test(trimmed)
      )) {
        // Clean up the section title
        const sectionTitle = trimmed
          .replace(/^\d+\.\s*/, '')
          .replace(/^[-*•]\s*/, '')
          .trim();
        
        if (sectionTitle.length > 3) {
          sections.push(sectionTitle);
        }
      }
    }
    
    // Default sections if outline parsing fails
    if (sections.length === 0) {
      return [
        'Executive Summary',
        'Understanding Your Requirements',
        'Our Approach and Methodology',
        'Project Timeline and Deliverables',
        'Team and Qualifications',
        'Budget and Investment',
        'Why Choose Us',
        'Next Steps'
      ];
    }
    
    return sections;
  };

  const handleCopyToClipboard = async () => {
    if (!generatedProposal) return;
    
    try {
      await navigator.clipboard.writeText(generatedProposal);
      toast.success("Proposal copied to clipboard");
    } catch (err) {
      toast.error("Failed to copy proposal");
    }
  };

  const handleExportProposal = () => {
    if (!generatedProposal) return;
    
    const blob = new Blob([generatedProposal], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `proposal-${projectId}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success("Proposal exported successfully");
  };

  const formatTime = (ms: number) => {
    if (ms < 1000) return `${ms}ms`;
    if (ms < 60000) return `${Math.round(ms / 1000)}s`;
    return `${Math.round(ms / 60000)}m ${Math.round((ms % 60000) / 1000)}s`;
  };

  return (
    <Card className="w-full">
      <CardHeader className="p-3 sm:p-6">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
          <div>
            <CardTitle className="flex items-center gap-2 text-lg sm:text-2xl">
              <Wand className="h-5 w-5 text-primary" />
              Auto-Generated Proposal
            </CardTitle>
            <CardDescription className="text-xs sm:text-sm">
              Generate a complete proposal automatically using your RFP analysis, outline, and knowledge base
            </CardDescription>
          </div>
          {!isGenerating && !generatedProposal && (
            <Button 
              onClick={handleGenerateProposal}
              className="w-full sm:w-auto flex items-center justify-center gap-2 bg-primary hover:bg-primary/90"
              disabled={!analysis || !proposalOutline}
            >
              <Wand className="h-4 w-4" />
              Generate Full Proposal
            </Button>
          )}
        </div>
        <Separator />
      </CardHeader>
      
      <CardContent className="space-y-4 sm:space-y-6 p-3 sm:p-6 pt-0">
        {/* Prerequisites Check */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
          <div className="flex items-center gap-2">
            {analysis ? (
              <CheckCircle className="h-4 w-4 text-green-500" />
            ) : (
              <div className="h-4 w-4 rounded-full border-2 border-muted-foreground" />
            )}
            <span className={analysis ? "text-foreground" : "text-muted-foreground"}>
              RFP Analysis Complete
            </span>
          </div>
          <div className="flex items-center gap-2">
            {proposalOutline ? (
              <CheckCircle className="h-4 w-4 text-green-500" />
            ) : (
              <div className="h-4 w-4 rounded-full border-2 border-muted-foreground" />
            )}
            <span className={proposalOutline ? "text-foreground" : "text-muted-foreground"}>
              Proposal Outline Ready
            </span>
          </div>
        </div>

        {/* Prerequisites Alert */}
        {(!analysis || !proposalOutline) && (
          <Alert>
            <FileText className="h-4 w-4" />
            <AlertDescription>
              Complete the RFP Summary and Proposal Outline sections first to generate your full proposal.
            </AlertDescription>
          </Alert>
        )}

        {/* Generation Progress */}
        {isGenerating && (
          <div className="space-y-4">
            <AIProgress 
              progress={generationStatus.progress} 
              label={generationStatus.currentSection || "Generating full proposal..."} 
            />
            <div className="text-sm text-muted-foreground text-center">
              This may take a few minutes as we generate all sections simultaneously
            </div>
          </div>
        )}

        {/* Error Display */}
        {error && (
          <Alert variant="destructive">
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {/* Generated Proposal Display */}
        {generatedProposal && (
          <div className="space-y-4">
            {/* Action Buttons */}
            <div className="grid grid-cols-2 sm:flex sm:flex-wrap gap-2">
              <Button 
                onClick={handleCopyToClipboard}
                variant="outline"
                size="sm"
                className="flex items-center gap-2"
              >
                <Copy className="h-4 w-4" />
                Copy
              </Button>
              <Button 
                onClick={handleExportProposal}
                variant="outline"
                size="sm"
                className="flex items-center gap-2"
              >
                <Download className="h-4 w-4" />
                Export
              </Button>
              <Button 
                onClick={handleGenerateProposal}
                variant="outline"
                size="sm"
                className="flex items-center gap-2"
                disabled={isGenerating}
              >
                <RefreshCw className="h-4 w-4" />
                Regenerate
              </Button>
              <SubmitToKnowledgeBaseButton
                proposalContent={generatedProposal}
                projectId={projectId}
              />
            </div>

            {/* Metadata */}
            {proposalMetadata && (
              <div className="space-y-4">
                {/* Main Stats */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-4 bg-muted rounded-lg">
                  <div className="text-center">
                    <div className="text-lg font-semibold">{proposalMetadata.sectionsGenerated}</div>
                    <div className="text-sm text-muted-foreground">Total Sections</div>
                  </div>
                  <div className="text-center">
                    <div className="text-lg font-semibold">{formatTime(proposalMetadata.totalProcessingTime)}</div>
                    <div className="text-sm text-muted-foreground">Generation Time</div>
                  </div>
                  <div className="text-center">
                    <div className="text-lg font-semibold">{Math.round(proposalMetadata.averageQuality)}%</div>
                    <div className="text-sm text-muted-foreground">Avg Quality</div>
                  </div>
                  <div className="text-center">
                    <div className="text-lg font-semibold">{Math.round(proposalMetadata.averageConfidence * 100)}%</div>
                    <div className="text-sm text-muted-foreground">Confidence</div>
                  </div>
                  {/* Show failed sections if any */}
                  {proposalMetadata.sectionsFailed && proposalMetadata.sectionsFailed > 0 && (
                    <>
                      <div className="text-center">
                        <div className="text-lg font-semibold text-green-600">{proposalMetadata.sectionsSuccessful}</div>
                        <div className="text-sm text-muted-foreground">Successful</div>
                      </div>
                      <div className="text-center">
                        <div className="text-lg font-semibold text-red-600">{proposalMetadata.sectionsFailed}</div>
                        <div className="text-sm text-muted-foreground">Failed</div>
                      </div>
                    </>
                  )}
                </div>
                
                {/* Cost Optimization Stats - Collapsible */}
                {proposalMetadata.costOptimization?.enabled && (
                  <Collapsible>
                    <div className="p-4 bg-green-50 dark:bg-green-950 border border-green-200 dark:border-green-800 rounded-lg">
                      <CollapsibleTrigger className="flex items-center gap-2 w-full">
                        <CheckCircle className="h-4 w-4 text-green-600" />
                        <span className="font-medium text-green-800 dark:text-green-200">AI Cost Optimization Active</span>
                        <span className="text-sm text-green-600 dark:text-green-400 ml-1">~{proposalMetadata.costOptimization.avgCostReduction}% savings</span>
                        <ChevronDown className="h-4 w-4 text-green-600 ml-auto transition-transform" />
                      </CollapsibleTrigger>
                      <CollapsibleContent>
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm mt-3">
                          <div>
                            <div className="text-lg font-semibold text-green-700 dark:text-green-300">
                              ~{proposalMetadata.costOptimization.avgCostReduction}%
                            </div>
                            <div className="text-green-600 dark:text-green-400">Cost Reduction</div>
                          </div>
                          <div>
                            <div className="text-lg font-semibold text-green-700 dark:text-green-300">
                              {proposalMetadata.costOptimization.tierDistribution.low}
                            </div>
                            <div className="text-green-600 dark:text-green-400">Fast (Haiku)</div>
                          </div>
                          <div>
                            <div className="text-lg font-semibold text-green-700 dark:text-green-300">
                              {proposalMetadata.costOptimization.tierDistribution.medium}
                            </div>
                            <div className="text-green-600 dark:text-green-400">Balanced (Sonnet 3.5)</div>
                          </div>
                          <div>
                            <div className="text-lg font-semibold text-green-700 dark:text-green-300">
                              {proposalMetadata.costOptimization.tierDistribution.high}
                            </div>
                            <div className="text-green-600 dark:text-green-400">Quality (Sonnet 4)</div>
                          </div>
                        </div>
                      </CollapsibleContent>
                    </div>
                  </Collapsible>
                )}
              </div>
            )}

            {/* Failed Sections Warning */}
            {proposalMetadata?.sectionsFailed > 0 && (
              <Alert className="border-yellow-200 bg-yellow-50 dark:border-yellow-800 dark:bg-yellow-950">
                <AlertDescription className="text-yellow-800 dark:text-yellow-200">
                  <strong>Partial Generation:</strong> {proposalMetadata.sectionsFailed} section(s) could not be generated due to rate limiting or other issues. 
                  These sections have placeholder content and should be completed manually or regenerated individually.
                </AlertDescription>
              </Alert>
            )}

            {/* Proposal Content */}
            <div className="border rounded-lg p-3 sm:p-6 bg-background max-h-[600px] overflow-y-auto">
              <div className="prose prose-sm max-w-none dark:prose-invert">
                <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed">
                  {generatedProposal}
                </pre>
              </div>
            </div>
          </div>
        )}

        {/* Getting Started Help */}
        {!isGenerating && !generatedProposal && analysis && proposalOutline && (
          <Alert>
            <Wand className="h-4 w-4" />
            <AlertDescription>
              Ready to generate! Click "Generate Full Proposal" to create a complete proposal using all your project data and knowledge base.
            </AlertDescription>
          </Alert>
        )}
      </CardContent>
    </Card>
  );
}