import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Loader2, Wand, Download, RefreshCw, FileText, Copy, CheckCircle } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/components/AuthProvider";
import { AIProgress } from "@/components/shared/AIProgress";

interface AutoGeneratedProposalProps {
  projectId: string;
  analysis: string | null;
  proposalOutline: string | null;
}

interface GenerationStatus {
  status: 'not_started' | 'in_progress' | 'completed' | 'failed';
  progress: number;
  currentSection?: string;
  error?: string;
}

interface ProposalMetadata {
  generatedAt: string;
  totalProcessingTime: number;
  sectionsGenerated: number;
  sectionsSuccessful?: number;
  sectionsFailed?: number;
  averageQuality: number;
  averageConfidence: number;
  sectionMetrics: Array<{
    section: string;
    quality: number;
    confidence: number;
    processingTime: number;
  }>;
  failedSections?: Array<{
    title: string;
    error: string;
  }>;
}

export function AutoGeneratedProposal({ 
  projectId, 
  analysis, 
  proposalOutline 
}: AutoGeneratedProposalProps) {
  const { session } = useAuth();
  const user = session?.user;
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationStatus, setGenerationStatus] = useState<GenerationStatus>({
    status: 'not_started',
    progress: 0
  });
  const [generatedProposal, setGeneratedProposal] = useState<string | null>(null);
  const [proposalMetadata, setProposalMetadata] = useState<ProposalMetadata | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleGenerateProposal = async () => {
    if (!user?.id || !analysis || !proposalOutline) {
      toast.error("Missing required data", {
        description: "Please ensure you have completed the RFP analysis and proposal outline first."
      });
      return;
    }

    setIsGenerating(true);
    setError(null);
    setGenerationStatus({ status: 'in_progress', progress: 0 });

    try {
      console.log('Starting full proposal generation...');
      
        const { data, error: functionError } = await supabase.functions.invoke(
          'generate-full-proposal',
          {
            body: {
              projectId,
              userId: user.id,
              strictMode: false
            }
          }
        );

      if (functionError) throw functionError;

      if (data.success) {
        setGeneratedProposal(data.proposal);
        setProposalMetadata(data.metadata);
        setGenerationStatus({ status: 'completed', progress: 100 });
        
        toast.success("Full proposal generated successfully!", {
          description: `Generated ${data.metadata.sectionsGenerated} sections in ${Math.round(data.metadata.totalProcessingTime / 1000)}s`
        });
      } else {
        throw new Error(data.error || 'Unknown error occurred');
      }

    } catch (err) {
      console.error('Error generating full proposal:', err);
      const errorMessage = err instanceof Error ? err.message : 'Failed to generate proposal';
      setError(errorMessage);
      setGenerationStatus({ status: 'failed', progress: 0, error: errorMessage });
      
      toast.error("Failed to generate proposal", {
        description: errorMessage
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopyToClipboard = async () => {
    if (!generatedProposal) return;
    
    try {
      await navigator.clipboard.writeText(generatedProposal);
      toast.success("Proposal copied to clipboard");
    } catch (err) {
      toast.error("Failed to copy proposal");
    }
  };

  const handleExportProposal = () => {
    if (!generatedProposal) return;
    
    const blob = new Blob([generatedProposal], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `proposal-${projectId}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success("Proposal exported successfully");
  };

  const formatTime = (ms: number) => {
    if (ms < 1000) return `${ms}ms`;
    if (ms < 60000) return `${Math.round(ms / 1000)}s`;
    return `${Math.round(ms / 60000)}m ${Math.round((ms % 60000) / 1000)}s`;
  };

  return (
    <Card className="w-full">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2">
              <Wand className="h-5 w-5 text-primary" />
              Auto-Generated Proposal
            </CardTitle>
            <CardDescription>
              Generate a complete proposal automatically using your RFP analysis, proposal outline, and knowledge base
            </CardDescription>
          </div>
          {!isGenerating && !generatedProposal && (
            <Button 
              onClick={handleGenerateProposal}
              className="flex items-center gap-2 bg-primary hover:bg-primary/90"
              disabled={!analysis || !proposalOutline}
            >
              <Wand className="h-4 w-4" />
              Generate Full Proposal
            </Button>
          )}
        </div>
        <Separator />
      </CardHeader>
      
      <CardContent className="space-y-6">
        {/* Prerequisites Check */}
        <div className="grid grid-cols-2 gap-4">
          <div className="flex items-center gap-2">
            {analysis ? (
              <CheckCircle className="h-4 w-4 text-green-500" />
            ) : (
              <div className="h-4 w-4 rounded-full border-2 border-muted-foreground" />
            )}
            <span className={analysis ? "text-foreground" : "text-muted-foreground"}>
              RFP Analysis Complete
            </span>
          </div>
          <div className="flex items-center gap-2">
            {proposalOutline ? (
              <CheckCircle className="h-4 w-4 text-green-500" />
            ) : (
              <div className="h-4 w-4 rounded-full border-2 border-muted-foreground" />
            )}
            <span className={proposalOutline ? "text-foreground" : "text-muted-foreground"}>
              Proposal Outline Ready
            </span>
          </div>
        </div>

        {/* Prerequisites Alert */}
        {(!analysis || !proposalOutline) && (
          <Alert>
            <FileText className="h-4 w-4" />
            <AlertDescription>
              Complete the RFP Summary and Proposal Outline sections first to generate your full proposal.
            </AlertDescription>
          </Alert>
        )}

        {/* Generation Progress */}
        {isGenerating && (
          <div className="space-y-4">
            <AIProgress 
              progress={generationStatus.progress} 
              label={generationStatus.currentSection || "Generating full proposal..."} 
            />
            <div className="text-sm text-muted-foreground text-center">
              This may take a few minutes as we generate all sections simultaneously
            </div>
          </div>
        )}

        {/* Error Display */}
        {error && (
          <Alert variant="destructive">
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {/* Generated Proposal Display */}
        {generatedProposal && (
          <div className="space-y-4">
            {/* Action Buttons */}
            <div className="flex flex-wrap gap-2">
              <Button 
                onClick={handleCopyToClipboard}
                variant="outline"
                size="sm"
                className="flex items-center gap-2"
              >
                <Copy className="h-4 w-4" />
                Copy
              </Button>
              <Button 
                onClick={handleExportProposal}
                variant="outline"
                size="sm"
                className="flex items-center gap-2"
              >
                <Download className="h-4 w-4" />
                Export
              </Button>
              <Button 
                onClick={handleGenerateProposal}
                variant="outline"
                size="sm"
                className="flex items-center gap-2"
                disabled={isGenerating}
              >
                <RefreshCw className="h-4 w-4" />
                Regenerate
              </Button>
            </div>

            {/* Metadata */}
            {proposalMetadata && (
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-4 bg-muted rounded-lg">
                <div className="text-center">
                  <div className="text-lg font-semibold">{proposalMetadata.sectionsGenerated}</div>
                  <div className="text-sm text-muted-foreground">Total Sections</div>
                </div>
                <div className="text-center">
                  <div className="text-lg font-semibold">{formatTime(proposalMetadata.totalProcessingTime)}</div>
                  <div className="text-sm text-muted-foreground">Generation Time</div>
                </div>
                <div className="text-center">
                  <div className="text-lg font-semibold">{Math.round(proposalMetadata.averageQuality)}%</div>
                  <div className="text-sm text-muted-foreground">Avg Quality</div>
                </div>
                <div className="text-center">
                  <div className="text-lg font-semibold">{Math.round(proposalMetadata.averageConfidence * 100)}%</div>
                  <div className="text-sm text-muted-foreground">Confidence</div>
                </div>
                {/* Show failed sections if any */}
                {proposalMetadata.sectionsFailed > 0 && (
                  <>
                    <div className="text-center">
                      <div className="text-lg font-semibold text-green-600">{proposalMetadata.sectionsSuccessful}</div>
                      <div className="text-sm text-muted-foreground">Successful</div>
                    </div>
                    <div className="text-center">
                      <div className="text-lg font-semibold text-red-600">{proposalMetadata.sectionsFailed}</div>
                      <div className="text-sm text-muted-foreground">Failed</div>
                    </div>
                  </>
                )}
              </div>
            )}

            {/* Failed Sections Warning */}
            {proposalMetadata?.sectionsFailed > 0 && (
              <Alert className="border-yellow-200 bg-yellow-50 dark:border-yellow-800 dark:bg-yellow-950">
                <AlertDescription className="text-yellow-800 dark:text-yellow-200">
                  <strong>Partial Generation:</strong> {proposalMetadata.sectionsFailed} section(s) could not be generated due to rate limiting or other issues. 
                  These sections have placeholder content and should be completed manually or regenerated individually.
                </AlertDescription>
              </Alert>
            )}

            {/* Proposal Content */}
            <div className="border rounded-lg p-6 bg-background max-h-[600px] overflow-y-auto">
              <div className="prose prose-sm max-w-none dark:prose-invert">
                <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed">
                  {generatedProposal}
                </pre>
              </div>
            </div>
          </div>
        )}

        {/* Getting Started Help */}
        {!isGenerating && !generatedProposal && analysis && proposalOutline && (
          <Alert>
            <Wand className="h-4 w-4" />
            <AlertDescription>
              Ready to generate! Click "Generate Full Proposal" to create a complete proposal using all your project data and knowledge base.
            </AlertDescription>
          </Alert>
        )}
      </CardContent>
    </Card>
  );
}