import { useState } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { FileEdit, BookOpen, Wand, Lock } from 'lucide-react';
import { useSubscriptionFeatures } from '@/hooks/use-subscription-features';
import { lazy, Suspense } from 'react';
import { ErrorBoundary } from '@/components/ErrorBoundary';
import { Loader2 } from 'lucide-react';
import { GatedFeature } from '@/components/subscription/GatedFeature';
import { TierBadge } from '@/components/subscription/TierBadge';

// Lazy load components
const ProposalDraft = lazy(() => import('@/components/project/proposal-draft/ProposalDraft').then(mod => ({ default: mod.ProposalDraft })));
const AutoGeneratedProposal = lazy(() => import('@/components/project/auto-proposal/AutoGeneratedProposal').then(mod => ({ default: mod.AutoGeneratedProposal })));

const SectionLoading = () => (
  <div className="flex justify-center items-center h-[300px]">
    <Loader2 className="h-8 w-8 animate-spin text-primary" />
  </div>
);

interface UnifiedProposalViewProps {
  projectId: string;
  analysis: string | null;
  proposalOutline: string | null;
}

const TIER_ORDER: Record<string, number> = {
  starter: 0,
  growth: 1,
  business: 2,
  enterprise: 3,
};

export function UnifiedProposalView({ projectId, analysis, proposalOutline }: UnifiedProposalViewProps) {
  const [activeTab, setActiveTab] = useState('draft');
  const { plan, isLoading } = useSubscriptionFeatures();

  const currentLevel = TIER_ORDER[plan] ?? 0;

  const tabs = [
    {
      id: 'draft',
      label: 'Draft',
      icon: FileEdit,
      requiredTier: null,
    },
    {
      id: 'compiled',
      label: 'Compiled',
      icon: BookOpen,
      requiredTier: 'growth' as const,
    },
    {
      id: 'auto',
      label: 'Auto-Generated',
      icon: Wand,
      requiredTier: 'business' as const,
    },
  ];

  const isLocked = (requiredTier: string | null): boolean => {
    if (!requiredTier || isLoading) return false;
    return currentLevel < (TIER_ORDER[requiredTier] ?? 1);
  };

  return (
    <div className="space-y-4">
      <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
        <TabsList className="grid w-full grid-cols-3">
          {tabs.map((tab) => {
            const locked = isLocked(tab.requiredTier);
            return (
              <TabsTrigger 
                key={tab.id} 
                value={tab.id}
                className="flex items-center gap-1.5"
              >
                <tab.icon className="h-4 w-4" />
                <span className={`text-[10px] sm:text-sm ${locked ? 'opacity-70' : ''}`}>{tab.label}</span>
                {locked && <Lock className="h-3 w-3 text-muted-foreground" />}
              </TabsTrigger>
            );
          })}
        </TabsList>

        <TabsContent value="draft" className="mt-4">
          <ErrorBoundary>
            <Suspense fallback={<SectionLoading />}>
              <ProposalDraft projectId={projectId} mode="draft" />
            </Suspense>
          </ErrorBoundary>
        </TabsContent>

        <TabsContent value="compiled" className="mt-4">
          <GatedFeature
            featureName="Compiled Proposal"
            requiredTier="growth"
            description="View your entire proposal as a single, continuous document. Perfect for final review and one-click copying."
            benefits={[
              "See your entire proposal as a continuous document",
              "Interactive table of contents with section navigation",
              "Print-ready preview matching final export",
              "Copy full proposal text with one click",
            ]}
          >
            <ErrorBoundary>
              <Suspense fallback={<SectionLoading />}>
                <ProposalDraft projectId={projectId} mode="compiled" />
              </Suspense>
            </ErrorBoundary>
          </GatedFeature>
        </TabsContent>

        <TabsContent value="auto" className="mt-4">
          <GatedFeature
            featureName="Auto-Generated Proposal"
            requiredTier="business"
            description="Let AI generate a complete proposal draft from your RFP analysis. Save hours of writing time."
            benefits={[
              "AI generates a full proposal from your RFP",
              "Customizable tone and style settings",
              "Section-by-section regeneration",
              "One-click integration with your draft",
            ]}
          >
            <ErrorBoundary>
              <Suspense fallback={<SectionLoading />}>
                <AutoGeneratedProposal 
                  projectId={projectId} 
                  analysis={analysis}
                  proposalOutline={proposalOutline}
                />
              </Suspense>
            </ErrorBoundary>
          </GatedFeature>
        </TabsContent>
      </Tabs>
    </div>
  );
}
