import { useState } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { FileEdit, BookOpen, Wand } from 'lucide-react';
import { useSubscriptionFeatures } from '@/hooks/use-subscription-features';
import { lazy, Suspense } from 'react';
import { ErrorBoundary } from '@/components/ErrorBoundary';
import { Loader2, Lock } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';

// Lazy load components
const ProposalDraft = lazy(() => import('@/components/project/proposal-draft/ProposalDraft').then(mod => ({ default: mod.ProposalDraft })));
const AutoGeneratedProposal = lazy(() => import('@/components/project/auto-proposal/AutoGeneratedProposal').then(mod => ({ default: mod.AutoGeneratedProposal })));

const SectionLoading = () => (
  <div className="flex justify-center items-center h-[300px]">
    <Loader2 className="h-8 w-8 animate-spin text-primary" />
  </div>
);

const FeatureLocked = ({ 
  featureName, 
  planName 
}: { 
  featureName: string;
  planName: string;
}) => {
  const navigate = useNavigate();
  
  return (
    <Card className="w-full max-w-md mx-auto mt-10">
      <CardHeader className="text-center pb-2">
        <Lock className="h-12 w-12 mx-auto text-muted-foreground mb-2" />
        <CardTitle>Feature Not Available</CardTitle>
        <CardDescription>
          {featureName} is available with {planName}
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col items-center pt-2">
        <Button 
          onClick={() => navigate('/subscription')}
          className="mt-2"
        >
          Upgrade Subscription
        </Button>
      </CardContent>
    </Card>
  );
};

interface UnifiedProposalViewProps {
  projectId: string;
  analysis: string | null;
  proposalOutline: string | null;
}

export function UnifiedProposalView({ projectId, analysis, proposalOutline }: UnifiedProposalViewProps) {
  const [activeTab, setActiveTab] = useState('draft');
  const { hasFeature, getPlanName } = useSubscriptionFeatures();

  const tabs = [
    {
      id: 'draft',
      label: 'Draft',
      icon: FileEdit,
      feature: 'proposal_draft',
    },
    {
      id: 'compiled',
      label: 'Compiled',
      icon: BookOpen,
      feature: 'compiled_draft',
    },
    {
      id: 'auto',
      label: 'Auto-Generated',
      icon: Wand,
      feature: 'auto_proposal_generation',
    },
  ];

  return (
    <div className="space-y-4">
      <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
        <TabsList className="grid w-full grid-cols-3">
          {tabs.map((tab) => (
            <TabsTrigger 
              key={tab.id} 
              value={tab.id}
              className="flex items-center gap-2"
              disabled={!hasFeature(tab.feature as any)}
            >
              <tab.icon className="h-4 w-4" />
              <span className="hidden sm:inline">{tab.label}</span>
            </TabsTrigger>
          ))}
        </TabsList>

        <TabsContent value="draft" className="mt-4">
          {hasFeature('proposal_draft') ? (
            <ErrorBoundary>
              <Suspense fallback={<SectionLoading />}>
                <ProposalDraft projectId={projectId} mode="draft" />
              </Suspense>
            </ErrorBoundary>
          ) : (
            <FeatureLocked 
              featureName="Proposal Draft" 
              planName={getPlanName('proposal_draft')} 
            />
          )}
        </TabsContent>

        <TabsContent value="compiled" className="mt-4">
          {hasFeature('compiled_draft') ? (
            <ErrorBoundary>
              <Suspense fallback={<SectionLoading />}>
                <ProposalDraft projectId={projectId} mode="compiled" />
              </Suspense>
            </ErrorBoundary>
          ) : (
            <FeatureLocked 
              featureName="Compiled Draft" 
              planName={getPlanName('compiled_draft')} 
            />
          )}
        </TabsContent>

        <TabsContent value="auto" className="mt-4">
          {hasFeature('auto_proposal_generation') ? (
            <ErrorBoundary>
              <Suspense fallback={<SectionLoading />}>
                <AutoGeneratedProposal 
                  projectId={projectId} 
                  analysis={analysis}
                  proposalOutline={proposalOutline}
                />
              </Suspense>
            </ErrorBoundary>
          ) : (
            <FeatureLocked 
              featureName="Auto-Generated Proposal" 
              planName={getPlanName('auto_proposal_generation')} 
            />
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}
