// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmopbbkfxkgzlbmhhgox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtb3BiYmtmeGtnemxibWhoZ294Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczMzAwMzYsImV4cCI6MjA1MjkwNjAzNn0.eFgn0DIR5LgS53r8r4-zb2vonhOpTFyXF3tJgtsuvhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);